name: AzerothCore Installation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server

      - name: Make install script executable
        run: chmod +x ./ACinstall.sh

      - name: Run ACinstall.sh
        env:
          INSTALL_DIR: "${GITHUB_WORKSPACE}/azerothcore"
          MYSQL_ROOT_PASSWORD: "test"
          SERVER_IP: "127.0.0.1"
          REALM_NAME: "MyRealm"
          INSTALL_PLAYERBOTS: "y"
        run: |
          yes | ./ACinstall.sh  # Automatically sends 'y' for confirmation prompt
