name: AzerothCore Installation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo service mysql start
          # Set a password for the mysql root user, and skip security checks.
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${{ secrets.MYSQL_ROOT_PASSWORD }}';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Make install script executable
        run: chmod +x ./ACinstall.sh

      - name: Run ACinstall.sh
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }} # use secrets instead of environment variable
          INSTALL_PLAYERBOTS: y # set to yes for automatic install during github action
          SERVER_IP: "127.0.0.1"
          REALM_NAME: "MyRealm"
        run: |
          yes | sudo ./ACinstall.sh
