name: Test AzerothCore Installation Script

on:
  push:
    branches:
      - main  # Or any branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  # Checks out the code so that your install script is available

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            cmake \
            make \
            gcc \
            g++ \
            clang \
            libssl-dev \
            libbz2-dev \
            libreadline-dev \
            libncurses-dev \
            libboost-all-dev \
            lsb-release \
            gnupg \
            wget \
            p7zip-full \
            mysql-server \
            libmysqlclient-dev \
            build-essential

      - name: Run ACinstall.sh script
        run: |
          chmod +x ./ACinstall.sh  # Make sure the script is executable
          INSTALL_DIR="${GITHUB_WORKSPACE}/azerothcore"
          MYSQL_ROOT_PASSWORD="test"  # Provide a root password
          SERVER_IP="127.0.0.1"  # Provide the server IP
          REALM_NAME="MyRealm"  # Provide the realm name
          INSTALL_PLAYERBOTS="y"  # Whether to install Playerbots (y/n)
          export INSTALL_DIR MYSQL_ROOT_PASSWORD SERVER_IP REALM_NAME INSTALL_PLAYERBOTS
          echo "Running ACinstall.sh script..."
          ./ACinstall.sh  # Run the install script with the passed directory
