name: Test AzerothCore Installation Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Run ACinstall.sh script
        run: |
          chmod +x ./ACinstall.sh  # Make sure the script is executable
          # Set a temporary directory for the installation if needed
          INSTALL_DIR="${GITHUB_WORKSPACE}/azerothcore"
          export INSTALL_DIR
          ./ACinstall.sh  # Run the install script with the passed directory
