name: AzerothCore Installation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          # Set a password for the mysql root user, and skip security checks.
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${{ secrets.MYSQL_ROOT_PASSWORD }}';"
          sudo mysql -e "FLUSH PRIVILEGES;"
          # Start the service
          sudo service mysql start
          # Add bind-address = 0.0.0.0 to config so it listens on all ports.
          sudo sed -i 's/^#bind-address/#bind-address/' /etc/mysql/mysql.conf.d/mysqld.cnf
          sudo sed -i '$a bind-address = 0.0.0.0' /etc/mysql/mysql.conf.d/mysqld.cnf
          # Restart the server after making changes to the config.
          sudo service mysql restart
          # Add a small wait to make sure the service is running.
          sleep 10
          sudo systemctl status mysql

      - name: Check MySQL service status
        run: |
          sudo service mysql start
          sleep 10
          sudo systemctl status mysql

      - name: Make install script executable
        run: chmod +x ./ACinstall.sh

      - name: Run ACinstall.sh
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }} # use secrets instead of environment variable
          INSTALL_PLAYERBOTS: y # set to yes for automatic install during github action
          SERVER_IP: "127.0.0.1"
          REALM_NAME: "MyRealm"
        run: |
          yes | sudo ./ACinstall.sh
